In [1]:
print("hello colab")

hello colab


In [4]:
import torch #파이토치를 사용하겠다는 선언

a = torch.Tensor(5) #Tensor 파이토치에서 어레이나 데이터를 다룰때 그 하나하나 data를 tensor라고 부름

print(a)
#여기까지 tensor 선언, 프린트

tensor([1., 1., 1., 1., 1.])


In [5]:
a = torch.ones(5)#1로 초기화 된 5칸 배열생성
print(a)

b = a.numpy() #tensor-> numpy
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [7]:
c = torch.from_numpy(b) #numpy->tensor
print(c)

tensor([1., 1., 1., 1., 1.])
